server:
    port: 9004
spring:
    jpa: 
        hibernate:
            ddl-auto: update
        show-sql: true
    datasource:
        url: jdbc:mysql://localhost:3306/asistencia
        username: root
        password: piero

    application:
        name: reclamo-service
    config:
        import:
        - optional:configserver:http://localhost:8888/
    cloud:
        config:
            username: root
            password: piero