spring:
    application:
        name: cliente-service
    config:
        import:
        - optional:configserver:http://localhost:8888/
    cloud:
        config:
            username: root
            password: piero