server:
    port: 8888
spring:
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/pierotoscano1496/asistencia-microservices.git
                    search-paths:
                    - config-data
                    username: ${GIT_USER}
                    password: ${GIT_PASSWORD}
    security:
        user:
            name: root
            password: piero